web:
  image: nginx:1.23.1-alpine
  volumes:
   - ./templates:/etc/nginx/templates
   - ./nginx/conf.d:/etc/nginx/conf.d
   - ./ssl:/etc/ssl
   - ./www/public:/usr/share/nginx/html
  ports:
   - "443:443"
  # environment:
  #  - NGINX_HOST=foobar.com
  #  - NGINX_PORT=80